package com.tangotab.web;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.beanutils.BeanUtils;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.tangotab.business.UserBO;
import com.tangotab.dao.pojo.User;
import com.tangotab.exception.ApplicationException;
import com.tangotab.util.TangoTabUtility;
import com.tangotab.util.TangotabConstants;
import com.tangotab.web.form.UserForm;

public class AdClientRegAction extends BaseAction {
	public static Logger log = LoggerFactory.getLogger(UserRegAction.class);
	private UserBO userBo = com.tangotab.businessImpl.BusinessFactory.getUserBO();

	@Override
	public ActionForward performExecute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		String page;
		UserForm userForm = (UserForm) form;
		User user = new User();

		ActionMessages messages = new ActionMessages();

		/* Test whether emailId exists for this role */
		if (userBo.checkUserAvailability(userForm.getEmailId(), TangotabConstants.RESTAURANT_OWNER)) {
			messages.add("message", new ActionMessage("errors.emailexist", "Email already exists"));
			saveMessages(request, messages);
			return mapping.findForward(TangotabConstants.CLIENT_FAILURE);

		}

		try {
			BeanUtils.copyProperties(user, userForm);
		} catch (Exception e) {
			messages.add("message", new ActionMessage("errors.misc", "Copy Properties Failed"));
			saveMessages(request, messages);
			return mapping.findForward(TangotabConstants.CLIENT_FAILURE);
		}

		try {
			/* For a new guest, billingmethod and billing type are defaultly set to one, and
			 * password is autogenerated */
			String password = TangoTabUtility.generateRandomCode();
			user.setPassword(password);
			user.setBillingMethodId(1);
			user.setBillingTypeId(1);
			userBo.saveRestaurantClient(user, "send");
			messages.add("message", new ActionMessage("errors.emailexist",
					"Client added successfully"));
			saveMessages(request, messages);
			page = TangotabConstants.CLIENT_SUCCESS;
		} catch (ApplicationException e) {
			messages.add(ActionMessages.GLOBAL_MESSAGE, new ActionMessage(e.getCode()));
			saveMessages(request, messages);
			return mapping.findForward(TangotabConstants.CLIENT_FAILURE);
		}

		return mapping.findForward(page);
	}
}